import React from 'react';
import App from './App.js';

export const CoachImageMaps = {
    'Jorge Sampaoli ' : require('./teams/Argentina/coach/jorgesampaoli.jpg'),
    'Bert Van Marwijk ' : require('./teams/Australia/coach/bertvanmarwijk.jpg'),
    'Roberto Martinez ' : require('./teams/Belgium/coach/robertomartinez.jpg'),
    'Tite ' : require('./teams/Brazil/coach/tite.jpg'),
    'Jose Pekerman ' : require('./teams/Colombia/coach/josepekerman.jpg'),
    'Oscar Ramirez ' : require('./teams/CostaRica/coach/oscarramirez.jpg'),
    'Zlatko Dalic ' : require('./teams/Croatia/coach/zlatkodalic.jpg'),
    'Age Hareide ' : require('./teams/Denmark/coach/agehareide.jpg'),
    'Hector Cuper ' : require('./teams/Egypt/coach/hectorcuper.jpg'),
    'Gareth Southgate ' : require('./teams/England/coach/garethsouthgate.jpg'),
    'Didier Deschamps ' : require('./teams/France/coach/didierdeschamps.jpg'),
    'Joachim Loew ' : require('./teams/Germany/coach/joachimloew.jpg'),
    'Heimir Hallgrimsson ' : require('./teams/Iceland/coach/heimirhallgrimsson.jpg'),
    'Carlos Queiroz ' : require('./teams/Iran/coach/carlosqueiroz.jpg'),
    'Akira Nishino ' : require('./teams/Japan/coach/akiranishino.jpg'),
    'Shin Taeyong ' : require('./teams/KoreaRepublic/coach/shintaeyong.jpg'),
    'Juan Carlos Osorio ' : require('./teams/Mexico/coach/juancarlososorio.jpg'),
    'Herve Renard ' : require('./teams/Morocco/coach/herverenard.jpg'),
    'Gernot Rohr ' : require('./teams/Nigeria/coach/gernotrohr.jpg'),
    'Hernan Gomez ' : require('./teams/Panama/coach/hernangomez.jpg'),
    'Ricardo Gareca ' : require('./teams/Peru/coach/ricardogareca.jpg'),
    'Adam Nawalka ' : require('./teams/Poland/coach/adamnawalka.jpg'),
    'Fernando Santos ' : require('./teams/Portugal/coach/fernandosantos.jpg'),
    'Stanislav Cherchesov ' : require('./teams/Russia/coach/stanislavcherchesov.jpg'),
    'Juan Antonio Pizzi ' : require('./teams/SaudiArabia/coach/juanantoniopizzi.jpg'),
    'Aliou Cisse ' : require('./teams/Senegal/coach/alioucisse.jpg'),
    'Mladen Krstajic ' : require('./teams/Serbia/coach/mladenkrstajic.jpg'),
    'Fernando Hierro ' : require('./teams/Spain/coach/fernandohierro.jpg'),
    'Janne Andersson ' : require('./teams/Sweden/coach/janneandersson.jpg'),
    'Vladimir Petkovic ' : require('./teams/Switzerland/coach/vladimirpetkovic.jpg'),
    'Nabil Maaloul ' : require('./teams/Tunisia/coach/nabilmaaloul.jpg'),
    'Oscar Tabarez ' : require('./teams/Uruguay/coach/oscartabarez.jpg'),
}