import React from 'react';
import App from './App.js'

export const ImageMap = {
    'Argentina' : require('./img/Argentina.png'),
    'Australia' : require('./img/Australia.png'),
    'Belgium' : require('./img/Belgium.png'),
    'Brazil' : require('./img/Brazil.png'),
    'Colombia' : require('./img/Colombia.png'),
    'Costa Rica' : require('./img/Costa_Rica.png'),
    'Croatia' : require('./img/Croatia.png'),
    'Denmark' : require('./img/Denmark.png'),
    'Egypt' : require('./img/Egypt.png'),
    'England' : require('./img/England.png'),
    'France' : require('./img/France.png'),
    'Germany' : require('./img/Germany.png'),
    'Iceland' : require('./img/Iceland.png'),
    'Iran' : require('./img/Iran.png'),
    'Japan' : require('./img/Japan.png'),
    'Korea Republic' : require('./img/Korea_Republic.png'),
    'Mexico' : require('./img/Mexico.png'),
    'Morocco' : require('./img/Morocco.png'),
    'Nigeria' : require('./img/Nigeria.png'),
    'Panama' : require('./img/Panama.png'),
    'Peru' : require('./img/Peru.png'),
    'Poland' : require('./img/Poland.png'),
    'Portugal' : require('./img/Portugal.png'),
    'Russia' : require('./img/Russia.png'),
    'Saudi Arabia' : require('./img/Saudi_Arabia.png'),
    'Senegal' : require('./img/Senegal.png'),
    'Serbia' : require('./img/Serbia.png'),
    'Spain' : require('./img/Spain.png'),
    'Sweden' : require('./img/Sweden.png'),
    'Switzerland' : require('./img/Switzerland.png'),
    'Tunisia' : require('./img/Tunisia.png'),
    'Uruguay' : require('./img/Uruguay.png'),
}
